In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd

In [16]:
#dataset
df = pd.read_csv('csv_files/toll_weather.csv')
print(df.ftypes)
df.head()

/home/slittle/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Unnamed: 0          int64:dense
EndZoneID           int64:dense
StartZoneID         int64:dense
StartDateTime      object:dense
EndDateTime        object:dense
TollRate          float64:dense
Direction          object:dense
Temperature       float64:dense
Pressure          float64:dense
Humidity          float64:dense
Wind Direction     object:dense
Wind Speed        float64:dense
Weather Desc       object:dense
Cloud Cover        object:dense
Visibility        float64:dense
dtype: object

,Unnamed: 0,EndZoneID,StartZoneID,StartDateTime,EndDateTime,TollRate,Direction,Temperature,Pressure,Humidity,Wind Direction,Wind Speed,Weather Desc,Cloud Cover,Visibility
0,1940034,3120,3100,2018-06-07 15:18:00+00:00,2018-06-07 15:24:00+00:00,0.0,E,24.0,763.6,57.0,Wind blowing from the south-southeast,4.0,NaN,"Scattered clouds (40-50%) 1650 m, broken cloud...",16.0
1,1940033,3130,3100,2018-06-07 15:18:00+00:00,2018-06-07 15:24:00+00:00,0.0,E,24.0,763.6,57.0,Wind blowing from the south-southeast,4.0,NaN,"Scattered clouds (40-50%) 1650 m, broken cloud...",16.0
2,1940289,3230,3210,2018-06-07 15:18:00+00:00,2018-06-07 15:24:00+00:00,0.0,W,24.0,763.6,57.0,Wind blowing from the south-southeast,4.0,NaN,"Scattered clouds (40-50%) 1650 m, broken cloud...",16.0
3,1940035,3110,3100,2018-06-07 15:18:00+00:00,2018-06-07 15:24:00+00:00,0.0,E,24.0,763.6,57.0,Wind blowing from the south-southeast,4.0,NaN,"Scattered clouds (40-50%) 1650 m, broken cloud...",16.0
4,1940036,3100,3100,2018-06-07 15:18:00+00:00,2018-06-07 15:24:00+00:00,0.0,E,24.0,763.6,57.0,Wind blowing from the south-southeast,4.0,NaN,"Scattered clouds (40-50%) 1650 m, broken cloud...",16.0

In [17]:
#engineer those features
df = df.drop(['Wind Direction', 'Cloud Cover', 'Weather Desc'], axis=1)
#df = pd.get_dummies(data=df, columns=['Weather Desc'])

In [18]:
#df['StartDateTime'] = pd.to_datetime(df['StartDateTime'])
#df['EndDateTime'] = pd.to_datetime(df['EndDateTime'])

In [19]:
import pylab
import calendar
import numpy as np
import pandas as pd
import seaborn as sn
from scipy import stats
#import missingno as msno
from datetime import datetime
import matplotlib.pyplot as plt
import warnings
pd.options.mode.chained_assignment = None
warnings.filterwarnings("ignore", category=DeprecationWarning)
%matplotlib inline

In [20]:
df["date"] = df.StartDateTime.apply(lambda x : x.split()[0])
df["hour"] = df.StartDateTime.apply(lambda x : x.split()[1].split(":")[0])
df["minute"] = df.StartDateTime.apply(lambda x : x.split()[1].split(":")[1])
df["weekday"] = df.date.apply(lambda dateString : calendar.day_name[datetime.strptime(dateString,"%Y-%m-%d").weekday()])
df["month"] = df.date.apply(lambda dateString : calendar.month_name[datetime.strptime(dateString,"%Y-%m-%d").month])
df = pd.get_dummies(data=df, columns=['weekday', 'month', 'Direction'])


#df["season"] = df.season.map({1: "Spring", 2 : "Summer", 3 : "Fall", 4 :"Winter" })
df.head()

,Unnamed: 0,EndZoneID,StartZoneID,StartDateTime,EndDateTime,TollRate,Temperature,Pressure,Humidity,Wind Speed,Visibility,date,hour,minute,weekday_Friday,weekday_Monday,weekday_Saturday,weekday_Sunday,weekday_Thursday,weekday_Tuesday,weekday_Wednesday,month_April,month_August,month_December,month_February,month_January,month_July,month_June,month_March,month_May,month_November,month_October,month_September,Direction_E,Direction_W
0,1940034,3120,3100,2018-06-07 15:18:00+00:00,2018-06-07 15:24:00+00:00,0.0,24.0,763.6,57.0,4.0,16.0,2018-06-07,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
1,1940033,3130,3100,2018-06-07 15:18:00+00:00,2018-06-07 15:24:00+00:00,0.0,24.0,763.6,57.0,4.0,16.0,2018-06-07,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
2,1940289,3230,3210,2018-06-07 15:18:00+00:00,2018-06-07 15:24:00+00:00,0.0,24.0,763.6,57.0,4.0,16.0,2018-06-07,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
3,1940035,3110,3100,2018-06-07 15:18:00+00:00,2018-06-07 15:24:00+00:00,0.0,24.0,763.6,57.0,4.0,16.0,2018-06-07,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
4,1940036,3100,3100,2018-06-07 15:18:00+00:00,2018-06-07 15:24:00+00:00,0.0,24.0,763.6,57.0,4.0,16.0,2018-06-07,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0

In [21]:
df = df.drop(columns=['StartDateTime', 'EndDateTime', 'date', 'Unnamed: 0'])
pd.set_option('display.max_columns', 50)
df.head()

,EndZoneID,StartZoneID,TollRate,Temperature,Pressure,Humidity,Wind Speed,Visibility,hour,minute,weekday_Friday,weekday_Monday,weekday_Saturday,weekday_Sunday,weekday_Thursday,weekday_Tuesday,weekday_Wednesday,month_April,month_August,month_December,month_February,month_January,month_July,month_June,month_March,month_May,month_November,month_October,month_September,Direction_E,Direction_W
0,3120,3100,0.0,24.0,763.6,57.0,4.0,16.0,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
1,3130,3100,0.0,24.0,763.6,57.0,4.0,16.0,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
2,3230,3210,0.0,24.0,763.6,57.0,4.0,16.0,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
3,3110,3100,0.0,24.0,763.6,57.0,4.0,16.0,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
4,3100,3100,0.0,24.0,763.6,57.0,4.0,16.0,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0

In [22]:
df.isna().sum()

EndZoneID               0
StartZoneID             0
TollRate                0
Temperature             0
Pressure              780
Humidity                0
Wind Speed           4764
Visibility            480
hour                    0
minute                  0
weekday_Friday          0
weekday_Monday          0
weekday_Saturday        0
weekday_Sunday          0
weekday_Thursday        0
weekday_Tuesday         0
weekday_Wednesday       0
month_April             0
month_August            0
month_December          0
month_February          0
month_January           0
month_July              0
month_June              0
month_March             0
month_May               0
month_November          0
month_October           0
month_September         0
Direction_E             0
Direction_W             0
dtype: int64

In [23]:
df['Pressure'] = df['Pressure'].fillna(0)
df['Wind Speed'] = df['Wind Speed'].fillna(0)
df['Visibility'] = df['Visibility'].fillna(0)
df.isna().sum()

EndZoneID            0
StartZoneID          0
TollRate             0
Temperature          0
Pressure             0
Humidity             0
Wind Speed           0
Visibility           0
hour                 0
minute               0
weekday_Friday       0
weekday_Monday       0
weekday_Saturday     0
weekday_Sunday       0
weekday_Thursday     0
weekday_Tuesday      0
weekday_Wednesday    0
month_April          0
month_August         0
month_December       0
month_February       0
month_January        0
month_July           0
month_June           0
month_March          0
month_May            0
month_November       0
month_October        0
month_September      0
Direction_E          0
Direction_W          0
dtype: int64

In [24]:
from sklearn.model_selection import train_test_split
y = df['TollRate']
X = df.drop(columns=['TollRate'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [25]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model = model.fit(X_train, y_train)
pred = model.predict(X_test)

In [26]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(pred, y_test)

1.841576296581117

In [27]:
pred

array([-1.26961136,  2.50834608,  0.54334974, ..., -0.09658289,
       -0.25074291,  1.56825352])

In [93]:
df.StartZoneID.unique()

array([3210, 3130, 3110, 3220, 3200, 3120, 3100, 3230])

In [94]:
df.EndZoneID.unique()

array([3220, 3130, 3110, 3120, 3210, 3230, 3200, 3100])

In [95]:
df.head()

,EndZoneID,StartZoneID,TollRate,Temperature,Pressure,Humidity,Wind Speed,Visibility,hour,minute,weekday_Friday,weekday_Monday,weekday_Saturday,weekday_Sunday,weekday_Thursday,weekday_Tuesday,weekday_Wednesday,month_April,month_August,month_December,month_February,month_January,month_July,month_June,month_March,month_May,month_November,month_October,month_September
0,3220,3210,0.0,24.0,763.6,57.0,4.0,16.0,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
1,3130,3130,0.0,24.0,763.6,57.0,4.0,16.0,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
2,3110,3110,0.0,24.0,763.6,57.0,4.0,16.0,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,3120,3110,0.0,24.0,763.6,57.0,4.0,16.0,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4,3130,3110,0.0,24.0,763.6,57.0,4.0,16.0,15,18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [113]:
df.groupby(['StartZoneID', 'EndZoneID']).mean()

                       TollRate  Temperature    Pressure   Humidity  \
StartZoneID EndZoneID
3100        3100       0.168536    18.731152  763.064148  63.523350
            3110       0.865130    18.731152  763.064148  63.523350
            3120       1.951163    18.731152  763.064148  63.523350
            3130       3.004676    18.640675  763.079860  63.486613
3110        3110       0.695735    18.730674  763.064139  63.522660
            3120       1.787378    18.730674  763.064139  63.522660
            3130       2.843082    18.640216  763.079846  63.485923
3120        3120       1.098609    18.729541  763.063742  63.520918
            3130       2.151440    18.639101  763.079437  63.484168
3130        3130       1.040293    18.638110  763.079295  63.482509
3200        3200       0.927544    18.729715  763.059861  63.511691
            3210       1.537704    18.729715  763.059861  63.511691
            3220       1.733697    18.729715  763.059861  63.511691
            3230       1.897631    18.639481  763.075460  63.474879
3210        3210       0.611312    18.730212  763.059875  63.513261
            3220       0.806687    18.730212  763.059875  63.513261
            3230       0.965634    18.639992  763.075473  63.476476
3220        3220       0.200181    18.730449  763.059635  63.512834
            3230       0.355024    18.640242  763.075228  63.476046
3230        3230       0.140953    18.641529  763.074965  63.476484

                       Wind Speed  Visibility  weekday_Friday  weekday_Monday  \
StartZoneID EndZoneID
3100        3100         3.919904   15.265998        0.154404        0.144589
            3110         3.919904   15.265998        0.154404        0.144589
            3120         3.919904   15.265998        0.154404        0.144589
            3130         3.925614   15.261922        0.154228        0.144237
3110        3110         3.919884   15.266215        0.154402        0.144634
            3120         3.919884   15.266215        0.154402        0.144634
            3130         3.925592   15.262144        0.154226        0.144282
3120        3120         3.919991   15.266159        0.154387        0.144590
            3130         3.925699   15.262089        0.154211        0.144237
3130        3130         3.925819   15.261974        0.154157        0.144221
3200        3200         3.921379   15.266611        0.154209        0.144629
            3210         3.921379   15.266611        0.154209        0.144629
            3220         3.921379   15.266611        0.154209        0.144629
            3230         3.927096   15.262556        0.154030        0.144279
3210        3210         3.921352   15.266659        0.154210        0.144642
            3220         3.921352   15.266659        0.154210        0.144642
            3230         3.927068   15.262605        0.154031        0.144291
3220        3220         3.921382   15.266564        0.154215        0.144659
            3230         3.927098   15.262510        0.154036        0.144309
3230        3230         3.927014   15.262425        0.154013        0.144288

                       weekday_Saturday  weekday_Sunday  weekday_Thursday  \
StartZoneID EndZoneID
3100        3100               0.143506        0.155148          0.138122
            3110               0.143506        0.155148          0.138122
            3120               0.143506        0.155148          0.138122
            3130               0.143092        0.154928          0.138647
3110        3110               0.143474        0.155102          0.138114
            3120               0.143474        0.155102          0.138114
            3130               0.143060        0.154882          0.138638
3120        3120               0.143463        0.155131          0.138149
            3130               0.143049        0.154911          0.138673
3130        3130               0.143044        0.154979          0.138648
3200        3200               0.143527        0.155289          0.138007
            3210               0.143527        0.155289          0.138007
            3220               0.143527        0.155289          0.138007
            3230               0.143115        0.155072          0.138528
3210        3210               0.143540        0.155301          0.137998
            3220               0.143540        0.155301          0.137998
            3230               0.143128        0.155084          0.138518
3220        3220               0.143535        0.155316          0.137983
            3230               0.143123        0.155100          0.138503
3230        3230               0.143136        0.155165          0.138472

                       weekday_Tuesday  weekday_Wednesday  month_April  \
StartZoneID EndZoneID
3100        3100              0.131962           0.132268     0.064044
            3110              0.131962           0.132268     0.064044
            3120              0.131962           0.132268     0.064044
            3130              0.131856           0.133012     0.065050
3110        3110              0.131967           0.132306     0.064135
            3120              0.131967           0.132306     0.064135
            3130              0.131861           0.133050     0.065142
3120        3120              0.132004           0.132277     0.064329
            3130              0.131898           0.133020     0.065338
3130        3130              0.131920           0.133031     0.065566
3200        3200              0.132104           0.132235     0.065561
            3210              0.132104           0.132235     0.065561
            3220              0.132104           0.132235     0.065561
            3230              0.132001           0.132976     0.066588
3210        3210              0.132117           0.132194     0.065579
            3220              0.132117           0.132194     0.065579
            3230              0.132014           0.132934     0.066605
3220        3220              0.132114           0.132179     0.065626
            3230              0.132010           0.132919     0.066653
3230        3230              0.132003           0.132923     0.066650

                       month_August  month_December  month_February  \
StartZoneID EndZoneID
3100        3100           0.075862        0.000219        0.063617
            3110           0.075862        0.000219        0.063617
            3120           0.075862        0.000219        0.063617
            3130           0.077053        0.000222        0.064617
3110        3110           0.075850        0.000219        0.063610
            3120           0.075850        0.000219        0.063610
            3130           0.077041        0.000222        0.064608
3120        3120           0.075821        0.000219        0.063607
            3130           0.077011        0.000222        0.064605
3130        3130           0.076979        0.000222        0.064600
3200        3200           0.075664        0.000218        0.063488
            3210           0.075664        0.000218        0.063488
            3220           0.075664        0.000218        0.063488
            3230           0.076849        0.000222        0.064482
3210        3210           0.075681        0.000218        0.063484
            3220           0.075681        0.000218        0.063484
            3230           0.076866        0.000222        0.064478
3220        3220           0.075695        0.000218        0.063477
            3230           0.076880        0.000222        0.064471
3230        3230           0.076885        0.000222        0.064456

                       month_January  month_July  month_June  month_March  \
StartZoneID EndZoneID
3100        3100            0.071912    0.076004    0.300120     0.071857
            3110            0.071912    0.076004    0.300120     0.071857
            3120            0.071912    0.076004    0.300120     0.071857
            3130            0.073041    0.077198    0.289129     0.072985
3110        3110            0.071901    0.075981    0.300032     0.071847
            3120            0.071901    0.075981    0.300032     0.071847
            3130            0.073030    0.077174    0.289043     0.072975
3120        3120            0.071874    0.075952    0.299917     0.071830
            3130            0.073002    0.077144    0.288930     0.072957
3130        3130            0.072971    0.077112    0.288808     0.072949
3200        3200            0.071715    0.075817    0.299253     0.071693
            3210            0.071715    0.075817    0.299253     0.071693
            3220            0.071715    0.075817    0.299253     0.071693
            3230            0.072837    0.077004    0.288280     0.072815
3210        3210            0.071710    0.075823    0.299233     0.071688
            3220            0.071710    0.075823    0.299233     0.071688
            3230            0.072833    0.077010    0.288261     0.072810
3220        3220            0.071702    0.075793    0.299211     0.071680
            3230            0.072825    0.076979    0.288240     0.072802
3230        3230            0.072808    0.077029    0.288188     0.072786

                       month_May  month_November  month_October  \
StartZoneID EndZoneID
3100        3100        0.065872        0.066003       0.071933
            3110        0.065872        0.066003       0.071933
            3120        0.065872        0.066003       0.071933
            3130        0.066906        0.067039       0.073063
3110        3110        0.065918        0.066005       0.071967
            3120        0.065918        0.066005       0.071967
            3130        0.066953        0.067041       0.073097
3120        3120        0.066024        0.066013       0.071918
            3130        0.067060        0.067049       0.073046
3130        3130        0.067120        0.067054       0.073015
3200        3200        0.066478        0.065899       0.071802
            3210        0.066478        0.065899       0.071802
            3220        0.066478        0.065899       0.071802
            3230        0.067518        0.066931       0.072926
3210        3210        0.066462        0.065895       0.071797
            3220        0.066462        0.065895       0.071797
            3230        0.067503        0.066927       0.072921
3220        3220        0.066477        0.065899       0.071789
            3230        0.067518        0.066930       0.072913
3230        3230        0.067580        0.066916       0.072897

                       month_September
StartZoneID EndZoneID
3100        3100              0.072557
            3110              0.072557
            3120              0.072557
            3130              0.073697
3110        3110              0.072536
            3120              0.072536
            3130              0.073675
3120        3120              0.072497
            3130              0.073635
3130        3130              0.073604
3200        3200              0.072413
            3210              0.072413
            3220              0.072413
            3230              0.073547
3210        3210              0.072430
            3220              0.072430
            3230              0.073564
3220        3220              0.072433
            3230              0.073567
3230        3230              0.073584

In [13]:
df.groupby('hour').mean()

,EndZoneID,StartZoneID,TollRate,Temperature,Pressure,Humidity,Wind Speed,Visibility,weekday_Friday,weekday_Monday,weekday_Saturday,weekday_Sunday,weekday_Thursday,weekday_Tuesday,weekday_Wednesday,month_April,month_August,month_December,month_February,month_January,month_July,month_June,month_March,month_May,month_November,month_October,month_September
hour,,,,,,,,,,,,,,,,,,,,,,,,,,,
00,3169.870831,3159.935416,0.000000,14.086735,763.693875,72.570311,3.049599,14.863313,0.156264,0.162874,0.169131,0.148292,0.120238,0.117816,0.125385,0.000000,0.000000,0.005046,0.117564,0.136233,0.000000,0.583228,0.040870,0.000000,0.117059,0.000000,0.000000
01,3169.778912,3159.889456,0.000000,21.678146,762.420519,77.624490,2.572704,15.240408,0.173214,0.175000,0.183588,0.177806,0.094388,0.092177,0.103827,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
02,3169.698997,3159.849498,0.000000,21.554181,762.394905,77.277815,2.956410,14.980513,0.191862,0.174136,0.170123,0.184058,0.085061,0.093757,0.101003,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
03,3169.588101,3159.794050,0.000000,20.949657,762.147386,78.879423,2.605351,14.380215,0.195036,0.182538,0.173209,0.149269,0.087309,0.106143,0.106495,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
04,3169.957811,3159.978905,0.000000,20.679138,762.251416,78.524259,2.919951,15.375597,0.187188,0.180526,0.173532,0.162429,0.096925,0.091373,0.108027,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
05,3169.775647,3159.887823,0.000000,20.242422,762.407989,79.700891,2.757236,15.725980,0.177941,0.168608,0.177342,0.181110,0.091197,0.097962,0.105840,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
06,3169.775720,3159.887860,0.000000,20.022683,762.556078,80.447116,2.633591,14.371319,0.174667,0.177555,0.183332,0.174497,0.085634,0.099312,0.105004,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
07,3169.779661,3159.889831,0.000000,20.631186,762.871797,79.580424,2.299661,14.282305,0.179831,0.182119,0.186610,0.156186,0.092288,0.097797,0.105169,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
08,3169.790140,3159.895070,0.000000,21.340190,763.292280,73.933461,2.869254,15.139241,0.174634,0.184377,0.190207,0.161143,0.090856,0.095436,0.103348,0.006662,0.009993,0.000000,0.000000,0.000000,0.011659,0.937125,0.007911,0.008328,0.000416,0.010826,0.007079
09,3170.022185,3160.060570,0.327039,20.618498,763.639390,68.916005,3.523469,15.268264,0.154117,0.159408,0.148797,0.152096,0.124905,0.131254,0.129422,0.086761,0.094482,0.000000,0.003941,0.004087,0.097641,0.372701,0.068305,0.083798,0.009925,0.089760,0.088600
10,3170.031892,3160.064356,0.814502,18.217188,764.179472,64.125472,3.889600,15.269781,0.153923,0.154009,0.138571,0.149945,0.134885,0.136491,0.132176,0.068466,0.076507,0.000000,0.066871,0.072701,0.076816,0.290803,0.073729,0.067574,0.063190,0.070414,0.072929
11,3170.013706,3160.045535,2.457922,19.243657,764.087011,60.780590,4.092148,15.433992,0.152295,0.154079,0.140005,0.152530,0.135228,0.134161,0.131701,0.068853,0.075930,0.000000,0.066066,0.073406,0.074783,0.288211,0.073636,0.068532,0.064425,0.072219,0.073940
12,3169.993281,3160.024538,3.958676,20.061656,763.926659,57.021156,4.227799,15.434952,0.154499,0.147955,0.144204,0.156614,0.132437,0.132706,0.131584,0.062100,0.078640,0.000000,0.067633,0.075602,0.076776,0.281263,0.075251,0.068632,0.065903,0.073849,0.074351
13,3170.015565,3160.046332,1.859969,20.655951,763.480293,54.798314,4.410749,15.515212,0.155330,0.135447,0.144071,0.162743,0.131716,0.135689,0.135005,0.068426,0.077771,0.000000,0.068517,0.076675,0.077523,0.280390,0.073889,0.063266,0.068196,0.071660,0.073689
14,3169.893099,3159.955363,0.578755,17.723566,763.489726,54.085090,4.537498,15.345903,0.164308,0.121535,0.153187,0.176723,0.122397,0.132187,0.129663,0.000000,0.000000,0.000000,0.139998,0.154201,0.000000,0.531766,0.043788,0.000000,0.130247,0.000000,0.000000
15,3169.783238,3159.891619,0.000000,26.862375,762.212286,55.102868,3.681585,15.817995,0.187144,0.093899,0.189012,0.192376,0.118285,0.113146,0.106138,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,3169.787028,3159.893514,0.000000,27.275367,761.941706,53.843351,4.430168,15.936355,0.195195,0.082813,0.194139,0.168177,0.154009,0.107542,0.098125,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,3169.767542,3159.883771,0.000000,27.317004,761.663065,54.725269,4.298493,15.889109,0.182437,0.082393,0.192165,0.172622,0.173052,0.105209,0.092122,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,3169.777670,3159.888835,0.230899,26.709844,761.584888,55.888432,4.385855,15.954406,0.180844,0.091187,0.179797,0.181086,0.162317,0.107701,0.097068,0.005639,0.011278,0.000000,0.000000,0.000000,0.011278,0.938779,0.006847,0.006847,0.000403,0.008861,0.010069
19,3169.987414,3160.029027,1.552774,23.767262,761.983837,59.289512,4.352512,15.641575,0.158462,0.128038,0.153900,0.156279,0.154999,0.122364,0.125958,0.078773,0.097629,0.000000,0.003637,0.004074,0.096756,0.370147,0.064310,0.086840,0.010476,0.093650,0.093708
20,3169.991738,3160.025016,1.454744,19.183289,762.853488,61.984736,4.089620,15.527313,0.156101,0.129207,0.141368,0.154217,0.155979,0.132627,0.130501,0.060553,0.077683,0.000000,0.061085,0.073235,0.075349,0.300103,0.069110,0.068093,0.068636,0.073489,0.072663
21,3170.004755,3160.037412,1.639315,18.449866,762.892709,64.812073,3.687569,15.500450,0.156284,0.131545,0.143009,0.155860,0.150263,0.128440,0.134599,0.065033,0.077804,0.000000,0.061877,0.071273,0.075913,0.294441,0.071387,0.068798,0.067950,0.072991,0.072533
22,3170.004183,3160.034196,1.300217,17.811138,761.373369,67.044884,3.731708,15.371107,0.154384,0.130379,0.141677,0.154977,0.154785,0.131758,0.132040,0.067905,0.076644,0.000000,0.063480,0.072348,0.075270,0.290268,0.070743,0.067493,0.070952,0.071421,0.073478
23,3169.977177,3160.020881,0.238669,17.972661,761.426070,69.295233,3.484623,15.261483,0.160586,0.126441,0.148713,0.158385,0.146358,0.127881,0.131636,0.057260,0.067498,0.000000,0.055609,0.065879,0.064875,0.388572,0.061023,0.054087,0.063071,0.061185,0.060942

In [116]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [115]:
weather = pd.read_csv('csv_files/weather.csv')
weather.head()

,Time,Temperature,Pressure,Humidity,Wind Direction,Wind Speed,Weather Desc,Cloud Cover,Visibility
0,15.07.2019 23:52,27.0,763.5,70.0,Wind blowing from the south-southeast,2.0,NaN,"Broken clouds (60-90%) 1440 m, broken clouds (...",16.0
1,15.07.2019 22:52,27.0,763.2,66.0,Wind blowing from the south-southeast,2.0,NaN,"Scattered clouds (40-50%) 2100 m, broken cloud...",16.0
2,15.07.2019 21:52,28.0,763.2,62.0,Wind blowing from the south-southeast,3.0,NaN,"Broken clouds (60-90%) 1950 m, broken clouds (...",16.0
3,15.07.2019 20:52,28.0,763.0,62.0,Wind blowing from the south-east,4.0,NaN,"Few clouds (10-30%) 2550 m, broken clouds (60-...",16.0
4,15.07.2019 19:52,31.0,762.7,46.0,Wind blowing from the north,3.0,NaN,"Few clouds (10-30%) 2400 m, scattered clouds (...",16.0

In [118]:
weather["hour"] = weather.Time.apply(lambda x : x.split()[1].split(":")[0])
weather.head()

,Time,Temperature,Pressure,Humidity,Wind Direction,Wind Speed,Weather Desc,Cloud Cover,Visibility,hour
0,15.07.2019 23:52,27.0,763.5,70.0,Wind blowing from the south-southeast,2.0,NaN,"Broken clouds (60-90%) 1440 m, broken clouds (...",16.0,23
1,15.07.2019 22:52,27.0,763.2,66.0,Wind blowing from the south-southeast,2.0,NaN,"Scattered clouds (40-50%) 2100 m, broken cloud...",16.0,22
2,15.07.2019 21:52,28.0,763.2,62.0,Wind blowing from the south-southeast,3.0,NaN,"Broken clouds (60-90%) 1950 m, broken clouds (...",16.0,21
3,15.07.2019 20:52,28.0,763.0,62.0,Wind blowing from the south-east,4.0,NaN,"Few clouds (10-30%) 2550 m, broken clouds (60-...",16.0,20
4,15.07.2019 19:52,31.0,762.7,46.0,Wind blowing from the north,3.0,NaN,"Few clouds (10-30%) 2400 m, scattered clouds (...",16.0,19

-12.0